### ISSUE TITLE
Gradle plugin fails to use universal APK when ABI splits are also present

### ISSUE THREAD

**Issue by jarl-balling** [MarathonLabs/marathon-gradle-plugin#2]
**Problem**

The project I've been working on uses the following Gradle/AGP splits configuration:
```
android {
    splits {
        abi {
            isEnable = true
            reset()
            include("armeabi-v7a", "arm64-v8a", "x86_64", "x86")
            isUniversalApk = true
        }
    }
}
```
Basically when we assemble the app we end up with all these different ABI .apks AND one universal .apk.
And then whenever I try to use `marathon-gradle-plugin` to start the runner (`./gradlew :baseApp:marathonDevelopmentDebugAndroidTest`) I get the following error:
```
> Task :baseapp:marathonDevelopmentDebugAndroidTestGenerateMarathonfile FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':baseapp:marathonDevelopmentDebugAndroidTestGenerateMarathonfile'.
> The Marathon plugin does not support abi splits for app APKs, but supports testing via a universal APK. Add the flag "universalApk true" in the android.splits.abi configuration.
``` 
Looking at [GenerateMarathonfileTask.mapAndroidOutputs()](https://github.com/MarathonLabs/marathon-gradle-plugin/blob/84d8f126186b46ef6b122941e2dcb20c1caf19a5/marathon-gradle-plugin/src/main/kotlin/com/malinskiy/marathon/gradle/task/GenerateMarathonfileTask.kt#L90) we can see that it simply counts how many artifacts there are. If there's more than 1 then it assumes that ABI-splits are present but fails to check if universal-APK is present as well.

**Solution**

Straightforward solution could look something likes this:
```
val application = when {
                        artifacts.elements.size > 1 -> artifacts.elements.firstOrNull { artifact ->
                            artifact.outputFile.contains("universal") }?.let { artifact ->
                            File(artifact.outputFile)
                        } ?: throw UnsupportedOperationException(
                                "The Marathon plugin does not support abi splits for app APKs, " +
                                    "but supports testing via a universal APK. "
                                    + "Add the flag \"universalApk true\" in the android.splits.abi configuration."
                            )
                        artifacts.elements.isEmpty() -> throw UnsupportedOperationException("No artifacts for variant $flavorName")
                        else -> File(artifacts.elements.first().outputFile)
                    }
```
Here we look for universalAPK before throwing the error. I've tried it out and it seems to work fine so I'll get on it.

**Comment by Malinskiy** [comment]
Closed via #3
